### ISSUE TITLE
Incorrect coordinates in database after insertion

### ISSUE THREAD

**Issue by jmeyers91** [joshswan/bookshelf-postgis#4]
I'm adding lat/lon points to my database as the type `geography(POINT, 4326)` using this plugin for handling converting to/from wkb but I'm finding the points in the database have an incorrect longitude value.

My table definition:

```
return knex.schema.createTableIfNotExists('upvotes', (table) => {
  table.increments('id').primary();
  table.string('device_id').notNullable();
  table.string('image_url').notNullable();
  table.specificType('location', 'geography(POINT, 4326)').notNullable();
  table.timestamps(true, true);
});
```

My table model:

```
const Upvotes = Model.extend({
  tableName: 'upvotes',
  geography: {
    location: ['latitude', 'longitude'],
  },
});
```

My insertion code:

```
async function insertUpvote({deviceId, location, imageURL}) {
  console.log(`Inserting upvote\n  deviceId: ${deviceId}\n  longitude: ${location.longitude}\n  latitude: ${location.latitude}\n  imageURL: ${imageURL}`);
  const upvote = await Upvotes.forge({
    latitude: location.latitude,
    longitude: location.longitude,
    device_id: deviceId,
    image_url: imageURL,
  }).save();

  return upvote.toJSON();
}

```

I've confirmed `insertUpvote` is receiving latitude `44.047726148147056` and longitude `-123.08937754046048`. But when I select the column using `ST_AsText`, the latitude is correct, but the longitude is `-56.910622459539525` (`SELECT ST_ASText(location) FROM upvotes;`). I'm receiving the same result when selecting using the model.

What is happening here?

**Comment by joshswan** [comment]
Your geography definition on the Upvotes model is reversed. It should be `location: ['longitude', 'latitude']`

**Comment by jmeyers91** [comment]
Haha. I feel pretty silly. Thanks again.
